:- op(1200, xfx, :+).

bus(('urn:example:re'(a,b),'urn:example:re'(a,c):+true)).
bus(('urn:example:e'(a,a):+'urn:example:re'(a,b))).
bus(('urn:example:e'(b,b):+'urn:example:re'(a,b))).
bus(('urn:example:e'(c,c):+'urn:example:re'(a,c))).
bus(('urn:example:re'(a,a):+'urn:example:e'(a,a))).
bus(('urn:example:re'(b,b):+'urn:example:e'(b,b))).
bus(('urn:example:re'(c,c):+'urn:example:e'(c,c))).
bus(('urn:example:not_re'(c,b):+'urn:example:re'(b,b))).
bus(('urn:example:not_re'(b,c):+'urn:example:re'(c,c))).
bus(('urn:example:not_e'(c,a):+'urn:example:not_re'(c,b),'urn:example:re'(a,b))).
bus(('urn:example:not_e'(c,b):+'urn:example:not_re'(c,b),'urn:example:re'(b,b))).
bus(('urn:example:not_e'(b,a):+'urn:example:not_re'(b,c),'urn:example:re'(a,c))).
bus(('urn:example:not_e'(b,c):+'urn:example:not_re'(b,c),'urn:example:re'(c,c))).
bus(('urn:example:not_e'(a,c):+'urn:example:not_e'(c,a))).
bus(('urn:example:not_e'(a,b):+'urn:example:not_e'(b,a))).
bus(('urn:example:r'(a,b):+'urn:example:re'(a,b),'urn:example:not_e'(a,b))).
bus(('urn:example:r'(a,c):+'urn:example:re'(a,c),'urn:example:not_e'(a,c))).
bus(('urn:example:r'(b,sk_0),'urn:example:r'(b,sk_0):+'urn:example:r'(a,b),'urn:example:r'(a,b))).
bus(('urn:example:r'(b,sk_0),'urn:example:r'(c,sk_0):+'urn:example:r'(a,b),'urn:example:r'(a,c))).
bus(('urn:example:re'(b,sk_0):+'urn:example:r'(b,sk_0))).
bus(('urn:example:re'(c,sk_0):+'urn:example:r'(c,sk_0))).
bus(('urn:example:r'(sk_0,sk_0),'urn:example:r'(sk_0,sk_0):+'urn:example:r'(b,sk_0),'urn:example:r'(b,sk_0))).
bus(('urn:example:not_re'(c,sk_0):+'urn:example:re'(b,sk_0))).
bus(('urn:example:not_re'(b,sk_0):+'urn:example:re'(c,sk_0))).
bus((true:+'urn:example:re'(b,sk_0),'urn:example:re'(c,sk_0))).
bus(('urn:example:e'(sk_0,sk_0):+'urn:example:re'(b,sk_0))).
bus(('urn:example:not_e'(c,c):+'urn:example:not_re'(c,sk_0),'urn:example:re'(c,sk_0))).
bus(('urn:example:not_e'(b,b):+'urn:example:not_re'(b,sk_0),'urn:example:re'(b,sk_0))).
bus(('urn:example:not_e'(b,sk_0):+'urn:example:e'(b,b),'urn:example:not_re'(b,sk_0))).
bus(('urn:example:not_e'(c,sk_0):+'urn:example:e'(c,c),'urn:example:not_re'(c,sk_0))).
bus(('urn:example:re'(sk_0,sk_0):+'urn:example:e'(sk_0,sk_0))).
bus(('urn:example:r'(b,b):+'urn:example:re'(b,b),'urn:example:not_e'(b,b))).
bus(('urn:example:r'(c,c):+'urn:example:re'(c,c),'urn:example:not_e'(c,c))).
bus(('urn:example:not_e'(sk_0,b):+'urn:example:not_e'(b,sk_0))).
bus(('urn:example:not_e'(sk_0,c):+'urn:example:not_e'(c,sk_0))).
